// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Analyzes respiration rate based on personal data and activity/condition checklist.
 *
 * - analyzeRespirationRate - A function that analyzes the respiration rate and provides feedback.
 * - AnalyzeRespirationRateInput - The input type for the analyzeRespirationRate function.
 * - AnalyzeRespirationRateOutput - The return type for the analyzeRespirationRate function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeRespirationRateInputSchema = z.object({
  age: z.number().describe('The age of the patient.'),
  gender: z.string().describe('The gender of the patient.'),
  weight: z.number().describe('The weight of the patient in kilograms.'),
  pastDisease: z
    .string()
    .optional()
    .describe(
      'Any past disease that affects respiration rate, or leave blank if none.'
    ),
  activityLevel: z.string().describe('The activity level of the patient.'),
  bodyPosture: z.string().describe('The body posture of the patient.'),
  stressLevel: z.string().describe('The stress level of the patient.'),
  hydrationStatus: z.string().describe('The hydration status of the patient.'),
  respirationRate: z.number().describe('The respiration rate of the patient.'),
});
export type AnalyzeRespirationRateInput = z.infer<
  typeof AnalyzeRespirationRateInputSchema
>;

const AnalyzeRespirationRateOutputSchema = z.object({
  analysis: z.string().describe('The analysis of the respiration rate.'),
  recommendations: z
    .string()
    .describe('Personalized recommendations based on the analysis.'),
  routine: z.string().describe('Suggested daily routine adjustments (e.g. walk more, specific exercises).'),
});
export type AnalyzeRespirationRateOutput = z.infer<
  typeof AnalyzeRespirationRateOutputSchema
>;

export async function analyzeRespirationRate(
  input: AnalyzeRespirationRateInput
): Promise<AnalyzeRespirationRateOutput> {
  return analyzeRespirationRateFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeRespirationRatePrompt',
  input: {schema: AnalyzeRespirationRateInputSchema},
  output: {schema: AnalyzeRespirationRateOutputSchema},
  prompt: `You are a healthcare expert specializing in respiration analysis.
You will receive patient data and generate a structured "Respiration Rate Report".

**Report Generation Logic:**

1.  **Patient Data**: Use the provided details: Age {{{age}}}, Weight {{{weight}}}kg, Gender {{{gender}}}, RR {{{respirationRate}}}bpm.
2.  **Interpretation**:
    *   Compare the measured RR to age-based reference ranges (Infants: 30-60, Toddlers: 24-40, Children: 18-30, Adults: 12-20).
    *   Determine status: "Normal", "Low (Bradypnea)", or "High (Tachypnea)".
3.  **Daily Routine Optimization**: Suggest specific lifestyle changes based on their profile. If they are sedentary, suggest walking. If stressed, suggest specific timed breaks.
4.  **Recommendations**: Provide immediate clinical-style advice.

Format the output fields as follows:
- 'analysis': A concise summary of the status and rationale.
- 'recommendations': Specific immediate actions (e.g., "Re-measure in 5 mins").
- 'routine': A 3-step daily routine plan to optimize their respiratory health (e.g. "1. Morning 15-min walk, 2. Afternoon hydration check, 3. Evening breathing exercises").
`,
});

const analyzeRespirationRateFlow = ai.defineFlow(
  {
    name: 'analyzeRespirationRateFlow',
    inputSchema: AnalyzeRespirationRateInputSchema,
    outputSchema: AnalyzeRespirationRateOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
