// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Analyzes respiration rate based on personal data and activity/condition checklist.
 *
 * - analyzeRespirationRate - A function that analyzes the respiration rate and provides feedback.
 * - AnalyzeRespirationRateInput - The input type for the analyzeRespirationRate function.
 * - AnalyzeRespirationRateOutput - The return type for the analyzeRespirationRate function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeRespirationRateInputSchema = z.object({
  age: z.number().describe('The age of the patient.'),
  gender: z.string().describe('The gender of the patient.'),
  weight: z.number().describe('The weight of the patient in kilograms.'),
  pastDisease: z
    .string()
    .optional()
    .describe(
      'Any past disease that affects respiration rate, or leave blank if none.'
    ),
  activityLevel: z.string().describe('The activity level of the patient.'),
  bodyPosture: z.string().describe('The body posture of the patient.'),
  stressLevel: z.string().describe('The stress level of the patient.'),
  dehydrationStatus: z.string().describe('The dehydration status of the patient.'),
  respirationRate: z.number().describe('The respiration rate of the patient.'),
});
export type AnalyzeRespirationRateInput = z.infer<
  typeof AnalyzeRespirationRateInputSchema
>;

const AnalyzeRespirationRateOutputSchema = z.object({
  analysis: z.string().describe('The analysis of the respiration rate.'),
  recommendations: z
    .string()
    .describe('Personalized recommendations based on the analysis.'),
});
export type AnalyzeRespirationRateOutput = z.infer<
  typeof AnalyzeRespirationRateOutputSchema
>;

export async function analyzeRespirationRate(
  input: AnalyzeRespirationRateInput
): Promise<AnalyzeRespirationRateOutput> {
  return analyzeRespirationRateFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeRespirationRatePrompt',
  input: {schema: AnalyzeRespirationRateInputSchema},
  output: {schema: AnalyzeRespirationRateOutputSchema},
  prompt: `You are a healthcare expert specializing in respiration analysis.

You will receive patient data including age, gender, weight, past diseases, activity level, body posture, stress level, dehydration status, and respiration rate.

Based on this information, you will analyze the respiration rate and provide personalized recommendations in points.

Use the following points to guide your analysis. Only variable data should change in the report.

- Age: Respiratory rate decreases from infancy to adulthood; adults typically fall within 12–20 breaths/min at rest, so any age change shifts the normal reference band used for alerts.
- Weight: Higher body mass can increase resting respiratory effort and push rates toward the upper end of normal, influencing whether a mild elevation is flagged as physiologic vs. abnormal.
- Gender: Females tend to have slightly higher resting rates and smaller airway/lung volumes, so similar readings may be interpreted as more expected in females than males within normal bounds.
- Hydration: Lower hydration can slow post-activity respiratory recovery and contribute to transient tachypnea; adequate hydration supports faster normalization after exertion.
- Stress level: Increased stress or anxiety commonly elevates respiratory rate; normalization after relaxation suggests a stress-mediated change rather than pathology.
- Posture: Upright or seated positions can yield slightly higher rates than supine; supine rest often facilitates quicker return to baseline after activity.


Patient Data:
Age: {{{age}}}
Gender: {{{gender}}}
Weight: {{{weight}}} kg
Past Disease: {{{pastDisease}}}
Activity Level: {{{activityLevel}}}
Body Posture: {{{bodyPosture}}}
Stress Level: {{{stressLevel}}}
Dehydration Status: {{{dehydrationStatus}}}
Respiration Rate: {{{respirationRate}}} breaths per minute

Analysis:
Recommendations:`, // Ensure Handlebars syntax is used correctly
});

const analyzeRespirationRateFlow = ai.defineFlow(
  {
    name: 'analyzeRespirationRateFlow',
    inputSchema: AnalyzeRespirationRateInputSchema,
    outputSchema: AnalyzeRespirationRateOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
